CREATE TABLE BUS_ROUTES_BUS_STOPS (
  id INTEGER PRIMARY KEY,
  bus_route_id INTEGER NOT NULL,
  stop_id INTEGER NOT NULL,
  stop_order INTEGER NOT NULL,
  FOREIGN KEY (bus_route_id) REFERENCES BUS_ROUTES (id) ON DELETE CASCADE,
  FOREIGN KEY (stop_id) REFERENCES BUS_STOPS (id) ON DELETE CASCADE
);